- name: Commit and Push changes
        run: |
          git config --global user.name 'News Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add index.html
          git commit -m "New News Update" || echo "No changes"
          git push
